# .circleci/config.yml

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            cd githubAPI567-hw4a
            python -m unittest test.py

workflows:
  build_and_test_workflow:
    jobs:
      - build-and-test
